"use client";

import Navbar from "@/components/Navbar";
import Footer from "@/components/footer/Footer";
import { motion } from "framer-motion";
import { Shield, Lock, Scale, Mail } from "lucide-react";
import Link from "next/link";

export default function PrivacyPolicyPage() {
  return (
    <div className="bg-[var(--background)] min-h-screen">
      <Navbar />
      
      <main className="pt-32 pb-24">
        <div className="max-w-4xl mx-auto px-6">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-center mb-16"
          >
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full glass border border-insight-teal/20 mb-6">
              <Shield className="w-3.5 h-3.5 text-insight-teal" />
              <span className="text-[10px] font-bold tracking-[0.2em] uppercase text-insight-teal">Legal Documentation</span>
            </div>
            <h1 className="text-4xl md:text-6xl font-black tracking-tighter mb-6">Privacy <span className="gradient-text">Policy</span></h1>
            <p className="text-[var(--text-muted)] font-bold uppercase tracking-widest text-xs">Last updated: April 30, 2026</p>
          </motion.div>

          <div className="glass p-12 rounded-[3rem] border border-white/10 prose prose-invert prose-insight max-w-none">
            <p className="lead text-lg text-[var(--text-muted)] mb-12">
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>

            <section className="mb-12">
              <div className="flex items-center gap-4 mb-6">
                <div className="w-10 h-10 rounded-xl bg-insight-teal/10 flex items-center justify-center text-insight-teal">
                  <Scale size={20} />
                </div>
                <h2 className="text-2xl font-bold m-0">Interpretation and Definitions</h2>
              </div>
              <div className="space-y-6 text-[var(--text-muted)]">
                <div>
                  <h3 className="text-white font-bold mb-2">Interpretation</h3>
                  <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                </div>
                <div>
                  <h3 className="text-white font-bold mb-2">Definitions</h3>
                  <ul className="grid grid-cols-1 md:grid-cols-2 gap-4 list-none p-0">
                    {[
                      { term: "Account", desc: "A unique account created for You to access our Service." },
                      { term: "Company", desc: "Refers to Dataflowra, 290 S Olive Street, Suite 520, Skyline Workspace, Los Angeles, CA 90015, USA." },
                      { term: "Cookies", desc: "Small files placed on Your computer or mobile device containing browsing history." },
                      { term: "Personal Data", desc: "Any information that relates to an identified or identifiable individual." },
                      { term: "Service", desc: "Refers to the Website (https://dataflowra.com)." },
                      { term: "Usage Data", desc: "Data collected automatically, generated by the use of the Service." }
                    ].map((item) => (
                      <li key={item.term} className="bg-white/5 p-4 rounded-2xl border border-white/5">
                        <strong className="text-insight-teal block mb-1">{item.term}</strong>
                        <span className="text-xs leading-relaxed">{item.desc}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </section>

            <section className="mb-12">
              <div className="flex items-center gap-4 mb-6">
                <div className="w-10 h-10 rounded-xl bg-aura-violet/10 flex items-center justify-center text-aura-violet">
                  <Lock size={20} />
                </div>
                <h2 className="text-2xl font-bold m-0">Collecting and Using Your Personal Data</h2>
              </div>
              <div className="space-y-8 text-[var(--text-muted)]">
                <div>
                  <h3 className="text-white font-bold mb-4">Types of Data Collected</h3>
                  <div className="grid gap-6">
                    <div className="glass border-white/5 p-6 rounded-2xl">
                      <h4 className="text-white font-bold mb-2 text-sm uppercase tracking-widest">Personal Data</h4>
                      <p className="text-sm mb-4">While using Our Service, We may ask You to provide Us with certain personally identifiable information:</p>
                      <div className="flex flex-wrap gap-2">
                        {["Email address", "First and last name", "Address", "City/ZIP"].map(t => (
                          <span key={t} className="px-3 py-1 bg-white/5 rounded-full text-[10px] font-bold text-white/60">{t}</span>
                        ))}
                      </div>
                    </div>
                    <div className="glass border-white/5 p-6 rounded-2xl">
                      <h4 className="text-white font-bold mb-2 text-sm uppercase tracking-widest">Usage Data</h4>
                      <p className="text-sm">Collected automatically when using the Service. May include Device's IP address, browser type, pages visited, and time spent on pages.</p>
                    </div>
                  </div>
                </div>

                <div>
                  <h3 className="text-white font-bold mb-4">Use of Your Personal Data</h3>
                  <ul className="space-y-3">
                    <li>To provide and maintain our Service and monitor usage.</li>
                    <li>To manage Your Account registration as a user.</li>
                    <li>For the performance of a purchase contract.</li>
                    <li>To contact You by email, phone, or SMS.</li>
                  </ul>
                </div>
              </div>
            </section>

            <section className="mb-12">
              <div className="flex items-center gap-4 mb-6">
                <div className="w-10 h-10 rounded-xl bg-insight-teal/10 flex items-center justify-center text-insight-teal">
                  <Scale size={20} />
                </div>
                <h2 className="text-2xl font-bold m-0">Retention and Deletion</h2>
              </div>
              <div className="space-y-6 text-[var(--text-muted)]">
                <div className="grid md:grid-cols-2 gap-6">
                  <div className="p-6 rounded-2xl bg-white/5">
                    <h4 className="text-white font-bold mb-2">Retention Periods</h4>
                    <ul className="text-xs space-y-2">
                      <li><strong>Account Info:</strong> Duration of relationship + 24 months.</li>
                      <li><strong>Support Data:</strong> 24 months from ticket closure.</li>
                      <li><strong>Usage Data:</strong> 24 months from collection.</li>
                    </ul>
                  </div>
                  <div className="p-6 rounded-2xl bg-white/5">
                    <h4 className="text-white font-bold mb-2">Your Rights</h4>
                    <p className="text-xs">You have the right to delete or request assistance in deleting Personal Data. You may update, amend, or delete information at any time in Your Account settings.</p>
                  </div>
                </div>
              </div>
            </section>

            <section className="mt-16 pt-16 border-t border-white/10">
              <div className="flex flex-col items-center text-center">
                <div className="w-16 h-16 rounded-3xl bg-insight-teal/10 flex items-center justify-center text-insight-teal mb-6">
                  <Mail size={32} />
                </div>
                <h2 className="text-2xl font-bold mb-4">Contact Our Legal Team</h2>
                <p className="text-[var(--text-muted)] mb-8 max-w-md">Questions about this Privacy Policy? Our data protection officer is here to help.</p>
                <div className="flex flex-col sm:flex-row gap-4">
                  <a href="mailto:help@dataflowra.com" className="px-8 py-4 rounded-2xl gradient-flow text-white font-black text-xs uppercase tracking-widest shadow-xl">help@dataflowra.com</a>
                  <Link href="/#contact" className="px-8 py-4 rounded-2xl glass border border-white/10 font-black text-xs uppercase tracking-widest">Contact Form</Link>
                </div>
              </div>
            </section>
          </div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
}
